Initial remote test
macarooni-man/auto-mcs pull request #71
Opened 2024-07-18 06:16 UTC by macarooni-man

- I made it work

2024-07-18 06:28 UTC, Alechuu requested changes

2024-07-18 06:28 UTC, Alechuu commented on source/remote.py
> +    for name, method in inspect.getmembers(instance, predicate=is_partial):
Add endpoint tag here based on the Object so it gets filtered on the docs page

2024-07-19 03:27 UTC, Alechuu requested changes

2024-07-19 03:27 UTC, Alechuu commented on source/remote.py
> +# This file abstracts all the program managers to control a server remotely
Remove these comments if not needed

2024-07-19 03:27 UTC, Alechuu commented on source/remote.py
> +        "url": "https://github.com/macarooni-man/auto-mcs/blob/main/source/gui-assets/logo.png?raw=true"
Maybe add this to constants? In case we wanna change it in the future

2024-07-19 03:27 UTC, Alechuu commented on source/remote.py
> +            # workers=1,
Remove this commented code if not needed

2024-07-19 03:27 UTC, Alechuu commented on source/remote.py
> +constants.api_manager.start()
Consider moving this to a background process

2024-07-19 03:30 UTC, Alechuu commented
Consider updating the `README.md` file on the `api` folder so it actually matches our current implementation of it and how it works

2024-07-19 15:35 UTC, macarooni-man commented on source/remote.py
> +            # workers=1,
I'm leaving this here because I'd like to use it later in the integration for optimization

2024-07-19 15:36 UTC, macarooni-man commented on source/remote.py
> +constants.api_manager.start()
Fixed in a468e43dfb26bc3530c1ce0f399edd1f5bdd3c58

2024-07-19 15:36 UTC, macarooni-man commented on source/remote.py
> +        "url": "https://github.com/macarooni-man/auto-mcs/blob/main/source/gui-assets/logo.png?raw=true"
Fixed in a468e43dfb26bc3530c1ce0f399edd1f5bdd3c58

2024-07-19 15:42 UTC, Alechuu approved these changes
LGTM 🎉

2024-07-19 15:42 UTC, macarooni-man commented on source/remote.py
> +# This file abstracts all the program managers to control a server remotely
I'm unsure if I need to move this file to /api, going to keep it in /source for testing at the moment. The import/path extension is only necessary if moved.

2024-07-19 15:45 UTC, Alechuu commented on source/remote.py
> +        try:
Is this try clause still needed?

2024-07-19 15:49 UTC, macarooni-man commented on source/remote.py
> +        try:
Yes, I need to write a proper handler because if the endpoint doesn't return anything, or fails to connect it will crash the whole software

2024-07-19 16:53 UTC, merged